[package]
name = "mkpw"
version = "0.1.1"
authors = ["chaosannals <chaosannals@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.10", features=["derive"]}
rand = "0.8.3"