[package]
name = "trail-rust"
version = "0.1.0"
authors = ["chaosannals <chaosannals@outlook.com>"]
edition = "2018"

[dependencies]
rand = "*"
actix-web = "*"
actix-rt = "*"
reqwest = { version = "0.10", features = ["blocking", "json"] }