@host = http://127.0.0.1:44321

###
# @name intoQueue
POST {{host}}/queue/into_queue HTTP/1.1
Content-Type: application/json

{
    "tag": "aaaaa",
    "message": "bbbbbb"
}

###
# @name intoBarQueue
POST {{host}}/queue/into_bar_queue HTTP/1.1
Content-Type: application/json

{
    "tag": 123234,
    "message": "bbbbbb"
}

###
# @name intoFooQueue
POST {{host}}/queue/into_foo_queue HTTP/1.1
Content-Type: application/json

{
    "tag": 123234,
    "message": "bbbbbb"
}

###
# @name intoBarQueue
POST {{host}}/queue/into_redis_jobs HTTP/1.1
Content-Type: application/json

{
    "tag": "123234",
    "message": "bbbbbb"
}

###
# @name intoRedisQueue
POST {{host}}/queue/into_redis_jobs HTTP/1.1
Content-Type: application/json

{
    "tag": "123234",
    "message": "bbbbbb"
}


###
# @name intoTaskQueue
POST {{host}}/queue/into_task_jobs HTTP/1.1
Content-Type: application/json

{
    "id": 123123
}