[package]
name = "svgdemo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.11.4"
usvg = "0.41.0"
resvg = "0.41.0"