[package]
name = "seaormdemo"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
sea-orm = { version = "^0.9.0", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros" ] }

[workspace]
members = [
    "migration",
]