import { SideBar } from "widgets/sidebar.slint";
import { CounterPage } from "pages/counter_page.slint";
import { AboutPage } from "pages/about_page.slint";

export component AppWindow inherits Window {
    HorizontalLayout {
        side-bar := SideBar {
            title: "Slint Custom Sidebar";
            model: ["Counter", "About", "CCCC"];
        }

        if (side-bar.current-item == 0): CounterPage{}
        if (side-bar.current-item == 1): AboutPage{}
        
    }
}
