[package]
name = "pdfdemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf.workspace=true
pdf_derive.workspace=true

image.workspace=true
anyhow.workspace=true