[workspace]

members = [
    "hostsman",
    "icedui",
    "imgui",
    "kasui",
    "mkpw",
    "mysql",
    "nwgui",
    "storage",
    "uniqrow",
    "wasmpd",
    "wasmprs",
    "wasmprslib",
    "winit",
]