[package]
name = "logpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# low
# aes = "0.8.2"
crypto = "0.5.0"