[package]
name = "jsonwebtokendemo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken.workspace = true
serde.workspace = true
anyhow.workspace = true
time.workspace = true