[package]
name = "lopdfdemo4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf={workspace=true, features = ["nom_parser"]}

anyhow.workspace=true

tokio={workspace=true, features = ["full"]}
