
import { Button, VerticalBox } from "std-widgets.slint";

export component CounterPage inherits VerticalBox {
    in-out property<int> counter: 42;
    callback request-increase-value();

    Text {
        text: "Counter: \{root.counter}";
    }
    Button {
        text: "Increase value";
        clicked => { 
            root.counter += 1;
            root.request-increase-value();
        }
    }
}